PierreBonsPlansBundle_homepage:
    path:     /articles/{page}
    defaults: { _controller: PierreBonsPlansBundle:BonsPlan:index, page: 1 }
    options:
        sitemap:
          priority: 1
          changefreq: daily
          section: bonsplan

PierreBonsPlansBundle_bonsplans_city:
    path:     /articles-par-ville/{city}/{page}
    defaults: { _controller: PierreBonsPlansBundle:BonsPlan:cityshow, page: 1 }
#    options:
#        sitemap:
#          priority: 1
#          changefreq: daily
#          section: bonsplan

PierreBonsPlansBundle_bonsplan_show:
    path:     /article/{slug}
    defaults: { _controller: PierreBonsPlansBundle:BonsPlan:show }
    requirements:
        _method:  GET|POST

PierreBonsPlansBundle_comment:
    path:     /comment/{bonsplans_id}
    defaults: { _controller: PierreBonsPlansBundle:Comment:new }
    requirements:
        _method:  POST
        bonsplan_id: \d+
