<?php

namespace Pierre\BonsPlansBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonsPlanCommentRepository extends \Doctrine\ORM\EntityRepository {

    public function getCommentsForBonsPlan($bonsplanID) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.bonsplan = :bonsplanID')
                ->addOrderBy('c.created', 'ASC')
                ->setParameter('bonsplanID', $bonsplanID);

        return $qb->getQuery()->getResult();
    }

    public function getLatestComments($limit = 10) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.id', 'DESC');

        if (false === is_null($limit)) {
            $qb->setMaxResults($limit);
        }

        return $qb->getQuery()
                        ->getResult();
    }

}
