<?php

namespace Pierre\BonsPlansBundle\Repository;

/**
 * BonsPlanRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonsPlanRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
