<?php

namespace Pierre\BonsPlansBundle\Repository;

/**
 * BonsPlanCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonsPlanCityRepository extends \Doctrine\ORM\EntityRepository
{
}
