<?php

namespace Pierre\BonsPlansBundle\Repository;

/**
 * BonsPlanCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonsPlanCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
