<?php

namespace Pierre\BonsPlansBundle\Repository;

/**
 * BonsPlanDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonsPlanDepartmentRepository extends \Doctrine\ORM\EntityRepository
{
}
