PierreConnaitresesaidesBundle_homepage:
    path:    /
    defaults:
       _controller: PierreConnaitresesaidesBundle:Connaitresesaides:index

PierreConnaitresesaidesBundle_aidesetudiants:
    path:    /aides-etudiants
    defaults:
       _controller: PierreConnaitresesaidesBundle:Connaitresesaides:aidesetudiants

PierreConnaitresesaidesBundle_aidesetudiants_resultats:
    path:    /aides-etudiants/resultats
    defaults:
       _controller: PierreConnaitresesaidesBundle:Connaitresesaides:aidesetudiantsresultats

PierreConnaitresesaidesBundle_sendresultsmail:
    path:    /aides-etudiants-francais/resultats/sendresultsmail
    defaults:
       _controller: PierreConnaitresesaidesBundle:Connaitresesaides:sendresultsmail
    requirements:
        _method: POST

