services:
#    pierre_site.example:
#        class: ConnaitresesaidesBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  pierre_site.antispam:
    class: Pierre\ConnaitresesaidesBundle\AntiSpam\AntiSpam
