pierre_bons_plans:
    resource: "@PierreBonsPlansBundle/Resources/config/routing.yml"
    prefix:   /bons-plans

pierre_site:
    resource: "@PierreSiteBundle/Resources/config/routing.yml"
    prefix:   /

#pierre_blog:
#    resource: "@PierreBlogBundle/Resources/config/routing.yml"
#    prefix:   /blog

pierre_connaitresesaides:
    resource: "@PierreConnaitresesaidesBundle/Resources/config/routing.yml"
    prefix:   /identifier-mes-aides

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /