# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html

services:
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    sendinblue:
        class: Pierre\SendinBlueBundle\Mailer\Mailer
        arguments: ["%sendinblue_contact%", "@doctrine.orm.entity_manager"]

    # SEO : PrestaSite
    app.sitemap.blog_post_subscriber:
        class: Pierre\BlogBundle\EventListener\SitemapBlogPostSubscriber
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: "kernel.event_subscriber", priority: 1 }

    app.sitemap.bonsplans_post_subscriber:
        class: Pierre\BonsPlansBundle\EventListener\SitemapBlogPostSubscriber
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: "kernel.event_subscriber", priority: 1 }