<?php

namespace Pierre\BlogBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository {

    public function getCommentsForBlog($blogId) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.blog = :blog_id')
                ->addOrderBy('c.created', 'ASC')
                ->setParameter('blog_id', $blogId);

        return $qb->getQuery()->getResult();
    }

    public function getLatestComments($limit = 10) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.id', 'DESC');

        if (false === is_null($limit)) {
            $qb->setMaxResults($limit);
        }

        return $qb->getQuery()
                        ->getResult();
    }

}
