<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * AdvantageDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvantageDepartmentRepository extends \Doctrine\ORM\EntityRepository
{
}
