<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * AidCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AidCityRepository extends \Doctrine\ORM\EntityRepository
{
}
