<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * AidStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AidStatutRepository extends \Doctrine\ORM\EntityRepository
{
}
