<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllCityName()
    {
        $qb = $this->createQueryBuilder('city')
            ->select('city.name')
            ->orderBy('city.name');

        return $qb->getQuery()
            ->getResult();
    }

    public function findAllCityOrdered()
    {
        $qb = $this->createQueryBuilder('city')
            ->select('city')
            ->orderBy('city.name');

        return $qb->getQuery()
            ->getResult();
    }


}
