<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * OfferRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
