<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * OfferStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferStatutRepository extends \Doctrine\ORM\EntityRepository
{
}
