<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * OfferTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
