<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * OfferDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferDepartmentRepository extends \Doctrine\ORM\EntityRepository
{
}
