<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * OfferCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferCityRepository extends \Doctrine\ORM\EntityRepository
{
}
