PierreSiteBundle_homepage:
    path:     /
    defaults: { _controller: PierreSiteBundle:Site:index }
    options:
        sitemap:
            priority: 1
            changefreq: daily
            section: site

PierreSiteBundle_apropos:
    path:     /a-propos
    defaults: { _controller: PierreSiteBundle:Site:apropos }

PierreSiteBundle_contact:
    path:     /contact
    defaults: { _controller: PierreSiteBundle:Site:contact }
    options:
        sitemap:
            priority: 0.1
            changefreq: monthly
            section: site

PierreSiteBundle_partnership:
    path:     /partenaires
    defaults: { _controller: PierreSiteBundle:Site:partenaires }

PierreSiteBundle_footer:
    path:     /footer
    defaults: { _controller: PierreSiteBundle:Site:footer }

PierreSiteBundle_modalsubscribe:
    path:     /modalsubscribe
    defaults: { _controller: PierreSiteBundle:Site:modalsubscribe }

PierreSiteBundle_mentionslegales:
    path:     /mentions-legales
    defaults: { _controller: PierreSiteBundle:Site:mentionslegales }

PierreSiteBundle_cgu:
    path:     /cgu
    defaults: { _controller: PierreSiteBundle:Site:cgu }

PierreSiteBundle_newsletter:
    path:     /newsletter
    defaults: { _controller: PierreSiteBundle:Site:newsletter }

PierreSiteBundle_sendcontactmail:
    path:     /sendcontactmail
    defaults: { _controller: PierreSiteBundle:Site:sendcontactmail }

PierreSiteBundle_dons:
    path:     /dons
    defaults: { _controller: PierreSiteBundle:Site:dons }

PierreSiteBundle_faq:
    path:     /faq
    defaults: { _controller: PierreSiteBundle:Site:faq }
