<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * AdvantageCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvantageCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
