<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * AdvantageCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvantageCityRepository extends \Doctrine\ORM\EntityRepository
{
}
