<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * AdvantageStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvantageStatutRepository extends \Doctrine\ORM\EntityRepository
{
}
