<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * AdvantageRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvantageRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
