<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * AidCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AidCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
