<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * AidDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AidDepartmentRepository extends \Doctrine\ORM\EntityRepository
{
}
