<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * AidRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AidRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
