<?php

namespace Pierre\ConnaitresesaidesBundle\Repository;

/**
 * OfferCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
