<?php

namespace Pierre\SiteBundle\Repository;

/**
 * GlobalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCitiesToAdd()
    {
        return $this->getGlobal("\$CITY_TO_ADD");
    }

    private function getGlobal($label)
    {
        $qb = $this->createQueryBuilder('globals')
            ->select('globals.value')
            ->where('globals.label = :label')
            ->setParameter('label', $label);

        return $qb->getQuery()
            ->getSingleScalarResult();
    }

    public function incrementNbCountSearch()
    {
        $qb = $this->createQueryBuilder('globals')
            ->select('globals.value')
            ->where('globals.label = :label')
            ->setParameter('label', "\$COUNT_SEARCH");

        $cpt = intval($qb->getQuery()->getSingleScalarResult()) + 1;

        $update = $this->createQueryBuilder('globals')
            ->update('PierreSiteBundle:Globals', 'globals')
            ->set('globals.value', strval($cpt))
            ->where('globals.label = :lab')
            ->setParameter('lab', '$COUNT_SEARCH')
            ->getQuery()->execute();

        return $update;
    }
}
