<?php

namespace Pierre\SiteBundle\Repository;

/**
 * GlobalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCitiesToAdd()
    {
        return $this->getGlobal("\$CITY_TO_ADD");
    }

    private function getGlobal($label)
    {
        $qb = $this->createQueryBuilder('globals')
            ->select('globals.value')
            ->where('globals.label = :label')
            ->setParameter('label', $label);

        return $qb->getQuery()
            ->getSingleScalarResult();
    }
}
