<?php

namespace Pierre\SiteBundle\Repository;

/**
 * MailListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailListRepository extends \Doctrine\ORM\EntityRepository
{
    public function isMailAlreadySaved($mail) {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.mail = :mail')
            ->setParameter('mail', $mail);

        return $qb->getQuery()->getResult();
    }
}
