<?php

namespace Pierre\SiteBundle\Repository;

/**
 * MainNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainNewsRepository extends \Doctrine\ORM\EntityRepository
{
}
