<?php

namespace Pierre\SiteBundle\Repository;

/**
 * MainNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainNewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMainNews()
    {
        $qb = $this->createQueryBuilder('m')
            ->select('m')
            ->orderBy('m.date', 'DESC');

        return $qb->getQuery()
            ->getResult();
    }
}
