<?php

namespace Pierre\SendinBlueBundle\Repository;

/**
 * BlockedMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockedMailRepository extends \Doctrine\ORM\EntityRepository
{
}
