PierreConnaitresesaidesBundle_homepage:
    path:    /
    defaults: { _controller: PierreConnaitresesaidesBundle:Connaitresesaides:index }

PierreConnaitresesaidesBundle_connaitresesaides:
    path:    /connaitre-ses-aides
    defaults:
       _controller: PierreConnaitresesaidesBundle:Connaitresesaides:connaitresesaides

PierreConnaitresesaidesBundle_connaitresesaides_resultats:
    path:    /connaitre-ses-aides/resultats
    defaults:
      _controller: PierreConnaitresesaidesBundle:Connaitresesaides:resultats
