<?php

namespace Pierre\SiteBundle\Repository;

/**
 * NewsletterMailListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterMailListRepository extends \Doctrine\ORM\EntityRepository
{
}
